version = 1

[[analyzers]]
name = "solhint"
type = "community"

[[analyzers]]
name = "slither"
type = "community"

[[analyzers]]
name = "kube-linter"
type = "community"

[[analyzers]]
name = "cfn-lint"
type = "community"

[[analyzers]]
name = "dart-analyze"
type = "community"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "kotlin"

  [analyzers.meta]
  runtime_version = "1.8"
  language_version = "1.7"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/MonkeyMarcel/besu"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"